### ISSUE TITLE
Better error message when using a parameter that is not defined

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nitor-deploy-tools#22]
Currently the error message looks like this (ndt 1.0a31)
```
Traceback (most recent call last):
  File "/usr/local/bin/cf-update-stack", line 11, in <module>
    sys.exit(update_stack())
  File "/usr/local/lib/python3.6/site-packages/n_utils/cli.py", line 489, in update_stack
    args.dry_run)
  File "/usr/local/lib/python3.6/site-packages/n_utils/cf_deploy.py", line 271, in deploy
    for key in list(template_parameters.keys()):
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by jsyrjala** [comment]
The same error message seems to also happen when the stack doesn't have any parameters (and stack doesn't use any parameters).

**Comment by jsyrjala** [comment]
Happens also in 1.0a47
